version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: clube_estilo_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    ports:
      - '5432:5432' # Uncomment if you want to access Postgres from host machine
    restart: unless-stopped
    healthcheck: # Garante que o banco está pronto antes da API iniciar
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8081:80'
    volumes:
    - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

  clube-estilo-api:
    build:
      context: . # Path to the directory with your NestJS app and Dockerfile
      dockerfile: Dockerfile
    container_name: clube-estilo-api
    ports:
      - '3000:3000' # Map your NestJS port
    env_file:
      - ./.env # Path to your NestJS .env file
    networks:
      - postgres
    depends_on:
      postgres: # Depende do serviço 'postgres' estar saudável
        condition: service_healthy
    command: ['sh', '-c', 'sleep 5 && npm run migration:run && npm run start:prod']
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
