version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: clube_estilo_postgres
    env_file:
      - ./.env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    networks:
      - postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - '8081:80'
    volumes:
    - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

  clube-estilo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clube-estilo-api
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: ['sh', '-c', 'sleep 10 && npm run migration:run && npm run start:prod']
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data: