version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8081:80'
    depends_on:
      - postgres
    networks:
      - postgres

  clube-estilo-api:
    build:
      context: . # Path to the directory with your NestJS app and Dockerfile
      dockerfile: Dockerfile
    container_name: clube-estilo-api
    ports:
      - '3000:3000' # Map your NestJS port
    env_file:
      - .env # Path to your NestJS .env file
    networks:
      - postgres
    depends_on:
      - postgres
    restart: always
    command: ["sh", "-c", "npm run migration:run && npm run start:prod"]

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
