export enum UserAffiliationEnum {
  USER = 'USER',
  CE_ADMIN = 'CE_ADMIN',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  SERVICE_PROVIDER_MANAGER = 'SERVICE_PROVIDER_MANAGER',
}
