export enum UserAffiliationEnum {
  USER = 'USER',
  CE_ADMIN = 'CE_ADMIN',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  SERVICE_PROVIDER_MANAGER = 'SERVICE_PROVIDER_MANAGER',
}

export enum UserGenderEnum {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum UserStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING = 'PENDING',
}
